[package]
name = "copystand"
version = "0.1.0"
authors = ["Tim Freund <tim@freunds.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
gphoto = "0.1.2"
rexiv2 = "0.9.1"
